# Generated by Django 5.0 on 2025-10-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('listing_date', models.DateField()),
                ('qib_subscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hni_subscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_subscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_sentiment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sector', models.CharField(max_length=100)),
                ('listing_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-listing_date'],
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('issue_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='In crores', max_digits=10)),
                ('lot_size', models.IntegerField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('qib_subscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hni_subscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retail_subscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_subscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gmp', models.DecimalField(decimal_places=2, default=0, help_text='Grey Market Premium', max_digits=10)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_gain', models.DecimalField(blank=True, decimal_places=2, help_text='In percentage', max_digits=10, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('lead_manager', models.CharField(blank=True, max_length=200)),
                ('registrar', models.CharField(blank=True, max_length=200)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='In crores', max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='In crores', max_digits=15, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('listed', 'Listed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='SimilarIPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_ipo_name', models.CharField(max_length=200)),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('similar_qib', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_hni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_retail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_issue_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_gmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_listing_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similar_sector', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_ipos', to='ipo_app.ipo')),
            ],
        ),
    ]
