# Generated by Django 5.0 on 2025-10-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalipo',
            old_name='gmp',
            new_name='listing_gains_percent',
        ),
        migrations.RenameField(
            model_name='historicalipo',
            old_name='hni_subscription',
            new_name='listing_gains_rs',
        ),
        migrations.RenameField(
            model_name='historicalipo',
            old_name='listing_gain',
            new_name='listing_price',
        ),
        migrations.RenameField(
            model_name='ipo',
            old_name='listing_gain',
            new_name='listing_gains_percentage',
        ),
        migrations.RenameField(
            model_name='ipo',
            old_name='hni_subscription',
            new_name='nii_subscription',
        ),
        migrations.RenameField(
            model_name='similaripo',
            old_name='similar_listing_gain',
            new_name='similar_listing_gains_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalipo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalipo',
            name='market_sentiment',
        ),
        migrations.RemoveField(
            model_name='historicalipo',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='ipo',
            name='gmp',
        ),
        migrations.AddField(
            model_name='historicalipo',
            name='issue_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalipo',
            name='nii_subscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalipo',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalipo',
            name='total_subscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipo',
            name='issue_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalipo',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalipo',
            name='qib_subscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalipo',
            name='retail_subscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
