# Generated by Django 5.0 on 2025-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0002_rename_gmp_historicalipo_listing_gains_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipo',
            name='company_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ipo',
            name='company_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
