# Generated by Django 5.0 on 2025-10-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0003_historicalipo_company_id_ipo_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipo',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ipo',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
