# Generated by Django 5.0 on 2025-10-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0004_historicalipo_company_logo_url_ipo_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='issue_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
