# Generated by Django 5.0 on 2025-10-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0005_alter_ipo_issue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='issue_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In crores', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
