# Generated by Django 5.0 on 2025-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0006_alter_ipo_issue_size_alter_ipo_lot_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipo',
            options={'ordering': ['-open_date']},
        ),
    ]
