# Generated by Django 5.0 on 2025-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0007_alter_ipo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipo',
            options={'ordering': ['open_date']},
        ),
        migrations.AddField(
            model_name='historicalipo',
            name='comapny_url_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ipo',
            name='comapny_url_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
