# Generated by Django 5.0 on 2025-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0008_alter_ipo_options_historicalipo_comapny_url_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='listing_gains_rs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
